name: Compile and Run Tests

on:
    pull_request:
      types:
        - opened
        - synchronize
        - reopened

jobs:
  compile:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Set up dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install git
      shell: powershell

    - name: Set up dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake
      shell: bash

    - name: Run Compile Action
      uses: ./.github/actions/compile
      with:
        path: src/
